name: EfendimDriverApp
description: A new Flutter application.

publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  android_intent: ^0.3.7+2
  app_settings: ^4.0.0
  audioplayers: null
  auto_size_text: ^2.1.0
  background_locator: ^1.1.5+1
  base_notifier: ^0.0.4
  bubble: ^1.1.9+1
  cached_network_image: ^2.2.0+1
  circular_countdown_timer: ^0.0.3
  cloud_firestore: null
  connectivity: ^0.4.8+6
  country_code_picker: ^2.0.1
  cupertino_icons: ^0.1.3
  device_id: ^0.2.0
  device_info: any
  dio: ^3.0.9
  dio_http_cache: ^0.2.6
  either_option: null
  expand_widget: ^2.1.0
  expansion_card: ^0.1.0
  firebase_auth: null
  firebase_core: null
  firebase_messaging:  
  firebase_storage: null
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.0
  flutter_calendar_carousel: ^1.4.12
  flutter_local_notifications: null
  flutter_phoenix: ^0.1.0
  flutter_polyline_points: ^0.2.2
  flutter_speed_dial: ^1.2.5
  flutter_spinkit: ^4.1.2+1
  pin_code_fields: ^6.1.0
  flutter_svg: ^0.20.0-nullsafety.3
  flutter_voximplant: ^2.2.0
  fluttertoast: ^3.1.3
  font_awesome_flutter: ^8.8.1
  geolocator: ^6.2.0
  get: ^4.1.4
  get_it: ^4.0.2
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.28+1
  grouped_buttons: ^1.0.4
  html_unescape: ^1.0.1+3
  carousel_slider: ^3.0.0
  http: ^0.12.1
  image_cropper: ^1.0.2
  image_picker: ^0.6.7+1
  contained_tab_bar_view: ^0.8.0
  intl: ^0.16.1
  intl_phone_field: ^1.4.2
  custom_switch: ^0.0.1
  location_permissions: ^2.0.5
  logger: ^0.9.4
  lottie: ^0.7.0+1
  material_design_icons_flutter: ^4.0.5955
  package_info: ^0.4.0+18
  permission_handler: ^5.0.1+1
  photo_view: ^0.9.0
  reactive_forms: ^9.0.2
  rxdart: ^0.24.1
  shared_preferences: ^0.5.7+3
  smooth_star_rating: ^1.1.1
  sms_autofill: ^2.0.0
  solid_bottom_sheet: ^0.1.9
  bottom_bar: ^1.2.4
  time: ^1.3.0
  toaster: null
  ui_utils: null
  url_launcher: ^5.4.11
  webview_flutter: ^2.0.4
  workmanager: ^0.2.2
  flutter_countdown_timer: ^3.0.0
  syncfusion_flutter_calendar: ^19.2.46
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
  modal_bottom_sheet: ^2.0.0
  path_provider: ^2.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf

  assets:
    - assets/mynotsound.mp3
    - assets/animation/
    - assets/images/
    - assets/icons/
    - assets/images/account/
    - assets/images/account/svg/
    - assets/images/icons/
 